# Generated by Django 5.1.3 on 2025-06-02 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_shipment_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveupdate',
            name='stages_label',
            field=models.CharField(choices=[('Dispatched', 'Dispatched'), ('In Transit', 'In Transit'), ('Withheld', 'Withheld'), ('Arrived', 'Arrived')], max_length=50),
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('ERROR', 'Error')], default='PENDING', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sid', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_logs', to='account.shipment')),
            ],
        ),
    ]
