# Generated by Django 5.1.3 on 2025-06-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_liveupdate_stages_label_messagelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagelog',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('UNDELIVERED', 'Undelivered'), ('FAILED', 'Failed'), ('ERROR', 'Error')], default='PENDING', max_length=50),
        ),
    ]
