# Generated by Django 5.1.3 on 2025-06-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_messagelog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveupdate',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='liveupdate',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
